import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Headbar from "@/components/NavBarComponents/Headbar";
import Footter from "@/components/NavBarComponents/Footter";
import { ClerkProvider } from "@clerk/nextjs";

// โหลดฟอนต์
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ✅ ตรวจสอบ environment variable ให้ชัดเจน
const publishableKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;

if (!publishableKey) {
  throw new Error(
    "❌ Missing NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY. \n" +
      "ไปเพิ่ม key ในไฟล์ .env.local หรือ Vercel Environment Variables ก่อนครับ!"
  );
}

// Root Layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider publishableKey={publishableKey}>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Headbar />
          {children}
          <Footter />
        </body>
      </html>
    </ClerkProvider>
  );
}