
import { Toaster } from "@/components/ui/sonner"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Headbar from "@/components/NavBarComponents/Headbar";
import Footter from "@/components/NavBarComponents/Footter";
import { ClerkProvider } from "@clerk/nextjs";
import LoadingScreen from "@/components/Animation/LoadingScreen";
import SmoothScroll from "@/components/Animation/SmoothScroll";
import FloatingCartWrapper from "@/components/NavBarComponents/FloatingCartWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const publishableKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY || "";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider publishableKey={publishableKey}>
      <html lang="en">
        <body className="font-sans bg-black text-white ml-0 mr-0 p-0 min-h-screen">
          <LoadingScreen />
          <SmoothScroll />
          <Headbar />
          {children}
          <FloatingCartWrapper />
          <Footter />
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
